# Generated by Django 4.1.1 on 2023-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_rate",
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=10),
        ),
    ]
