# Generated by Django 4.1.1 on 2023-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0003_spedition_alter_tour_spedition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="spedition",
            field=models.CharField(default="CTJ", max_length=40),
        ),
        migrations.DeleteModel(
            name="Spedition",
        ),
    ]
