# Generated by Django 4.1.1 on 2023-04-24 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0004_alter_tour_spedition_delete_spedition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spedition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="tour",
            name="spedition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="truck.spedition"
            ),
        ),
    ]
