# Generated by Django 4.1.1 on 2023-04-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0006_alter_tour_spedition_alter_tour_truck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="spedition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sped",
                to="truck.spedition",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="truck.truck"
            ),
        ),
    ]
