# Generated by Django 4.2.1 on 2023-06-01 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0007_alter_tour_spedition_alter_tour_truck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="name",
            field=models.CharField(default="Default", max_length=20),
        ),
        migrations.CreateModel(
            name="Raport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="documents/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
