# Generated by Django 4.2.1 on 2023-06-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0008_alter_truck_name_raport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Raport",
        ),
    ]
