# Generated by Django 4.2.1 on 2023-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0009_delete_raport"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="normalized_name",
            field=models.CharField(default="Default", max_length=20),
        ),
    ]
